"""schema with vk_ads support

Revision ID: 5b2edab7249d
Revises: 
Create Date: 2026-03-30 17:13:44.484360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2edab7249d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('oauth_token', sa.Text(), nullable=False),
    sa.Column('client_login', sa.String(length=255), nullable=True),
    sa.Column('counter_id', sa.BigInteger(), nullable=True),
    sa.Column('host_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metrika_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('counter_id', sa.BigInteger(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_metrika_id'), 'goals', ['metrika_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metrika_counter_id', sa.BigInteger(), nullable=True),
    sa.Column('webmaster_host_id', sa.String(length=255), nullable=True),
    sa.Column('direct_client_login', sa.String(length=255), nullable=True),
    sa.Column('vk_account_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('yandex_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('daily_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('strategy_type', sa.String(length=100), nullable=True),
    sa.Column('strategy_params', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_platform'), 'campaigns', ['platform'], unique=False)
    op.create_index(op.f('ix_campaigns_project_id'), 'campaigns', ['project_id'], unique=False)
    op.create_index(op.f('ix_campaigns_vk_id'), 'campaigns', ['vk_id'], unique=True)
    op.create_index(op.f('ix_campaigns_yandex_id'), 'campaigns', ['yandex_id'], unique=True)
    op.create_table('webmaster_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('position', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_text', 'date', 'device_type', name='uq_webmaster_query_text_date_device')
    )
    op.create_index(op.f('ix_webmaster_queries_date'), 'webmaster_queries', ['date'], unique=False)
    op.create_index(op.f('ix_webmaster_queries_project_id'), 'webmaster_queries', ['project_id'], unique=False)
    op.create_table('ad_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('yandex_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('region_ids', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_groups_platform'), 'ad_groups', ['platform'], unique=False)
    op.create_index(op.f('ix_ad_groups_vk_id'), 'ad_groups', ['vk_id'], unique=True)
    op.create_index(op.f('ix_ad_groups_yandex_id'), 'ad_groups', ['yandex_id'], unique=True)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_campaign_id'), 'ai_insights', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ai_insights_insight_type'), 'ai_insights', ['insight_type'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('conversions_count', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cost_per_conversion', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'goal_id', 'date', name='uq_conversion_campaign_goal_date')
    )
    op.create_index(op.f('ix_conversions_campaign_id'), 'conversions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_conversions_goal_id'), 'conversions', ['goal_id'], unique=False)
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('avg_cpc', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_position', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bounce_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'date', name='uq_daily_stats_campaign_date')
    )
    op.create_index(op.f('ix_daily_stats_campaign_id'), 'daily_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=False)
    op.create_table('ab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('variant_a_ids', sa.JSON(), nullable=False),
    sa.Column('variant_b_ids', sa.JSON(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('winner', sa.String(length=10), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('ai_analysis_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_insights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('yandex_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('title2', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('href', sa.Text(), nullable=True),
    sa.Column('display_url_path', sa.String(length=255), nullable=True),
    sa.Column('sitelinks', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('moderation_status', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_platform'), 'ads', ['platform'], unique=False)
    op.create_index(op.f('ix_ads_vk_id'), 'ads', ['vk_id'], unique=True)
    op.create_index(op.f('ix_ads_yandex_id'), 'ads', ['yandex_id'], unique=True)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('serving_status', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_yandex_id'), 'keywords', ['yandex_id'], unique=True)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'query_text', 'date', name='uq_search_query_campaign_text_date')
    )
    op.create_index(op.f('ix_search_queries_campaign_id'), 'search_queries', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_search_queries_date'), 'search_queries', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_queries_date'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_campaign_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_keywords_yandex_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_ads_yandex_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_vk_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_platform'), table_name='ads')
    op.drop_table('ads')
    op.drop_table('ab_tests')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_campaign_id'), table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_index(op.f('ix_conversions_goal_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_campaign_id'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_ai_insights_insight_type'), table_name='ai_insights')
    op.drop_index(op.f('ix_ai_insights_campaign_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_ad_groups_yandex_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_vk_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_platform'), table_name='ad_groups')
    op.drop_table('ad_groups')
    op.drop_index(op.f('ix_webmaster_queries_project_id'), table_name='webmaster_queries')
    op.drop_index(op.f('ix_webmaster_queries_date'), table_name='webmaster_queries')
    op.drop_table('webmaster_queries')
    op.drop_index(op.f('ix_campaigns_yandex_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_vk_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_project_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_platform'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_index(op.f('ix_goals_metrika_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_table('api_credentials')
    # ### end Alembic commands ###
