plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\harch\\OneDrive\\Рабочий стол\\cloude\\Artika\\landing\\family-day"
publishOrigin = "default"
base = "C:\\Users\\harch\\OneDrive\\Рабочий стол\\cloude\\Artika\\landing\\family-day"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]